=== Khandora/Parser/src/xml/computer.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="gameclub">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="computer" type="about_computer"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="about_computer">
        <xsd:sequence>
            <xsd:element name="about_computer" type="specifications" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="specifications">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="producer" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="cpu" type="xsd:string"/>
            <xsd:element name="cost" type="xsd:integer"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Khandora/Parser/src/xml/computer_xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gameclub xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xmlns="$LOCAL_SCHEMA$"
          xsd:noNamespaceSchemaLocation="computer.xsd">
    <computer>
        <about_computer>
            <name>ACOS System 1000</name>
            <producer>ACOS</producer>
            <type>Terminal</type>
            <cpu>Intel Pentium 4</cpu>
            <cost>750</cost>
        </about_computer>

        <about_computer>
            <name>HITAC E-800 Series</name>
            <producer>HITAC</producer>
            <type>Gaming</type>
            <cpu>Intel Core i7-9700k</cpu>
            <cost>1520</cost>
        </about_computer>

        <about_computer>
            <name>E575-5 231</name>
            <producer>Acer</producer>
            <type>Business</type>
            <cpu>Intel core i3-4700</cpu>
            <cost>950</cost>
        </about_computer>

        <about_computer>
            <name>ACOS System 1000</name>
            <producer>ACOS</producer>
            <type>Terminal</type>
            <cpu>Intel Pentium 4</cpu>
            <cost>750</cost>
        </about_computer>

        <about_computer>
            <name>HITAC E-800 Series</name>
            <producer>HITAC</producer>
            <type>Gaming</type>
            <cpu>Intel Core i7-9700k</cpu>
            <cost>1520</cost>
        </about_computer>

        <about_computer>
            <name>E575-5 231</name>
            <producer>Acer</producer>
            <type>Business</type>
            <cpu>Intel core i3-4700</cpu>
            <cost>950</cost>
        </about_computer>
    </computer>
</gameclub>
